name: UPDATE
on:
  workflow_dispatch:
    inputs:
      level:
        description: Logging Level
        required: true
        default: INFO
        type: choice
        options:
          - CRITICAL
          - FATAL
          - ERROR
          - WARNING
          - WARN
          - INFO
          - DEBUG
          - NOTSET
      pool:
        description: Number of threads
        required: true
        default: 8
      retry:
        description: Number of retries
        required: true
        default: 3
      time:
        description: Update wait time
        required: true
        default: 1
      args:
        description: args
        required: false
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          python main.py -l ${{ github.event.inputs.level || 'INFO' }} -p ${{ github.event.inputs.pool || 8 }} -r ${{ github.event.inputs.retry || 3 }} -t ${{ github.event.inputs.time || 1 }} -k ${{ secrets.KEY }} -u ${{ github.event.inputs.args }}